### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fvcr** [IGLOU-EU/go-wildcard#2]
Hi, I noticed that there was a re-licensing of the project, they changed from Apache License Version 2.0 to GNU Affero General Public License 3.0 or later.

Please take a look at this:
https://github.com/minio/minio/commit/069432566fcfac1f1053677cc925ddafd750730a
https://github.com/minio/pkg/blob/9979833e9530cdf64a107aebdcb05d154624b347/wildcard/match.go

Are you planning to do the same or will you keep the project with the Apache License Version 2.0?

**Comment by IGLOU-EU** [comment]
Nice catch @fvcr !

There is a re-licensing on the whole Minio project https://github.com/minio/minio/commit/069432566fcfac1f1053677cc925ddafd750730a

That's rough, but I can understand it. Some people don't hesitate to steel source code to make their own proprietary stuff.

But for this little lib, I think is use less. 
The externalization of Minio pkg tool, is very cool, but now we can select the sale library with different license.

But, what do you think about ?

**Comment by fvcr** [comment]
> But, what do you think about ?

I think you can keep the license as it is [(Apache License Version 2.0)](https://github.com/IGLOU-EU/go-wildcard/blob/9be10f2ad77a1827e258fcfbf9f923f9606a75c5/LICENSE).

I would point out that there was this licensing change to justify why your project is under Apache License Version 2.0 terms.

But I saw that you updated the [README.md](https://github.com/IGLOU-EU/go-wildcard/blob/9be10f2ad77a1827e258fcfbf9f923f9606a75c5/README.md), so everything looks fine to me.

Thanks!

**Comment by IGLOU-EU** [comment]
Thanks to you :)
