### ISSUE TITLE
create a new tag

### ISSUE THREAD

**Issue by caarlos0** [IGLOU-EU/go-wildcard#4]
running 

```
go mod init foo
go get github.com/IGLOU-EU/go-wildcard
echo 'package main

import (
	"fmt"

	wildcard "github.com/IGLOU-EU/go-wildcard"
)

func main() {
    str := "daaadabadmanda"
    
    pattern := "da*da*da*"
    result := wildcard.MatchSimple(pattern, str)
	fmt.Println(str, pattern, result)

    pattern = "?a*da*d?*"
    result = wildcard.Match(pattern, str)
	fmt.Println(str, pattern, result)
}
' > main.go

go mod tidy
```

results in both `github.com/IGLOU-EU/go-wildcard v1.0.2` and `git.iglou.eu/Imported/go-wildcard v1.0.1` being added to `go.mod` and `go.sum`.

My guess, after looking into the commits and some other things:

- changed the path on `go.mod` in d62667c9a7ccc52dd709a20c507329691a188f7c
- released v1.0.2
- a couple of hours later, noticed the import of the old path was still in the test file, fixed in commit 5dbd24971d263e4a859c743197cdc31173113f9e
- deleted tag v1.0.2 and tagged it again

At that point, Go mod proxy had already cached the broken version, so when you `go get` you get that one instead of the intended one.

My suggestion would be to release a v1.0.3 to fix that.

cc/ @muesli 

Cheers!

**Comment by IGLOU-EU** [comment]
I will do it as soon as possible! Thank you very much for this issue @caarlos0 !

**Comment by IGLOU-EU** [comment]
Check ! Thank again :)
