### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by muhlemmer** [IGLOU-EU/go-wildcard#8]
You do realize that when you fork code, the original copyright applies. That's why it's called COPYright. You can't release the same work (fork/copy/derative of the work) under another license. That's exactly what the GNU licenses are there for to prevent. All derivative works should also make their source code available under the same GNU Affero General Public License 3.0. 

Tl;Dr: https://www.tldrlegal.com/license/gnu-affero-general-public-license-v3-agpl-3-0

**Comment by IGLOU-EU** [comment]
Hi @muhlemmer 
thanks for your interest

You are absolutely right, a license cannot be changed during a fork.
However, this fork is made on a commit before the license change from the Minio project.
This is clearly indicated in the readme.

> This library remains under Apache License Version 2.0, but MinIO project is migrated to GNU Affero General Public License 3.0 or later from https://github.com/minio/minio/commit/069432566fcfac1f1053677cc925ddafd750730a

In this fork, the license is intended to `MinIO Cloud Storage`, but after the license change it is intended to `MinIO Project`.

I take no credit for the work done here, I even quote Minio in About.
Feel free to contribute to this fork. I plan to do so, but unfortunately haven't had the time yet :(

**Comment by muhlemmer** [comment]
My bet. Didn't read well then :)

**Comment by IGLOU-EU** [comment]
Hi @muhlemmer ,

After a lot of work and a full rewrite, the new implementation is done.
I keep the MinIO work (and license reference) only for the benchmarking comparison.

Thanks again for your interest,
Regards,
Adrien.
